// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SST.Infrastructure.Persistence;

#nullable disable

namespace SST.Infrastructure.Migrations
{
    [DbContext(typeof(SSTDbContext))]
    [Migration("20260710014442_AddMapaRiesgo")]
    partial class AddMapaRiesgo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SST.Domain.IPERC.Entities.DetalleIPERC", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsecuenciaId")
                        .HasColumnType("bigint");

                    b.Property<string>("DescripcionPeligro")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("EstadoImplementacion")
                        .HasColumnType("int");

                    b.Property<long>("EvaluacionInicialId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EvaluacionResidualId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCompromiso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaImplementacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<long>("MatrizIPERCId")
                        .HasColumnType("bigint");

                    b.Property<long>("PeligroId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResponsableImplementacionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tarea")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConsecuenciaId");

                    b.HasIndex("Estado");

                    b.HasIndex("EvaluacionInicialId");

                    b.HasIndex("EvaluacionResidualId");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("MatrizIPERCId");

                    b.HasIndex("PeligroId");

                    b.HasIndex("ResponsableImplementacionId");

                    b.ToTable("DetallesIPERC", (string)null);
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.DetalleIPERCControl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ControlId")
                        .HasColumnType("bigint");

                    b.Property<long>("DetalleIPERCId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("DetalleIPERCId");

                    b.ToTable("DetalleIPERCControles");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.DetalleIPERCEPP", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("DetalleIPERCId")
                        .HasColumnType("bigint");

                    b.Property<long>("EquipoProteccionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DetalleIPERCId");

                    b.HasIndex("EquipoProteccionId");

                    b.ToTable("DetalleIPERCEPP");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.EvaluacionRiesgo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsAceptable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("NivelRiesgoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("ProbabilidadId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RequiereAccion")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("SeveridadId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NivelRiesgoId");

                    b.HasIndex("ProbabilidadId");

                    b.HasIndex("SeveridadId");

                    b.ToTable("EvaluacionesRiesgo");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.MapaRiesgo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ArchivoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EstadoMapa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaElaboracion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("MatrizIPERCId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TipoArchivo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatrizIPERCId");

                    b.ToTable("MapasRiesgo");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.MatrizIPERC", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ActividadId")
                        .HasColumnType("bigint");

                    b.Property<string>("Alcance")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long?>("AprobadorId")
                        .HasColumnType("bigint");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EstadoMatriz")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("InstitucionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<long>("ProcesoId")
                        .HasColumnType("bigint");

                    b.Property<long>("PuestoTrabajoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResponsableId")
                        .HasColumnType("bigint");

                    b.Property<long>("SedeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("AprobadorId");

                    b.HasIndex("AreaId");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("ProcesoId");

                    b.HasIndex("PuestoTrabajoId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("SedeId");

                    b.ToTable("MatricesIPERC");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.NivelRiesgo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Aceptable")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Desde")
                        .HasColumnType("int");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Hasta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("NivelesRiesgo");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.Probabilidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Probabilidades");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.SeguimientoIPERC", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Archivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<long>("DetalleIPERCId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSeguimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<decimal>("PorcentajeAvance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoArchivo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Verificado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DetalleIPERCId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SeguimientosIPERC");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.Severidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Severidades");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Actividad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("InstitucionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("ProcesoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("ProcesoId");

                    b.ToTable("Actividades", (string)null);
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("InstitucionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("InstitucionId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Institucion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Nombre");

                    b.ToTable("Instituciones", (string)null);
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Proceso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("InstitucionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("InstitucionId");

                    b.ToTable("Procesos", (string)null);
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.PuestoTrabajo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("InstitucionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("InstitucionId");

                    b.ToTable("PuestosTrabajo", (string)null);
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Sede", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("InstitucionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("InstitucionId");

                    b.ToTable("Sedes", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.CategoriaPeligro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icono")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre");

                    b.ToTable("CategoriasPeligro", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.ClasificacionControl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Nombre");

                    b.ToTable("ClasificacionesControl", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.Consecuencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Clasificacion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("Fatalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IncapacidadPermanente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Nombre");

                    b.ToTable("Consecuencias", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.Control", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<long>("ClasificacionControlId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("EsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("Obligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("RequisitoLegal")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ResponsableSugerido")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClasificacionControlId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ColegioId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Nombre");

                    b.ToTable("Controles", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.EquipoProteccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("EsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NormaTecnica")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("RequiereCapacitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiereMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("TipoEquipoProteccionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.Property<int?>("VidaUtilMeses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ColegioId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Nombre");

                    b.HasIndex("TipoEquipoProteccionId");

                    b.ToTable("EquiposProteccion", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.Peligro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fuente")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Medio")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Receptor")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Recomendaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RequisitoLegal")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("TipoPeligroId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Nombre");

                    b.HasIndex("TipoPeligroId");

                    b.ToTable("Peligros", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.PeligroConsecuencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsecuenciaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("PeligroId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConsecuenciaId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("PeligroId", "ConsecuenciaId")
                        .IsUnique();

                    b.ToTable("PeligrosConsecuencias", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.PeligroControl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<long>("ControlId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Obligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("PeligroId")
                        .HasColumnType("bigint");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("PeligroId", "ControlId")
                        .IsUnique();

                    b.ToTable("PeligrosControles", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.PeligroEquipoProteccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<long>("EquipoProteccionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Obligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("PeligroId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EquipoProteccionId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("PeligroId", "EquipoProteccionId")
                        .IsUnique();

                    b.ToTable("PeligrosEquiposProteccion", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.TipoEquipoProteccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("EsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ColegioId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Nombre");

                    b.ToTable("TiposEquipoProteccion", (string)null);
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.TipoPeligro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<long>("CategoriaPeligroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPeligroId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre");

                    b.ToTable("TiposPeligro", (string)null);
                });

            modelBuilder.Entity("SST.Domain.Security.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ColegioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("InstitucionId")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("SedeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UsuarioActualizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.DetalleIPERC", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.Consecuencia", "Consecuencia")
                        .WithMany()
                        .HasForeignKey("ConsecuenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.IPERC.Entities.EvaluacionRiesgo", "EvaluacionInicial")
                        .WithMany()
                        .HasForeignKey("EvaluacionInicialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.IPERC.Entities.EvaluacionRiesgo", "EvaluacionResidual")
                        .WithMany()
                        .HasForeignKey("EvaluacionResidualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SST.Domain.IPERC.Entities.MatrizIPERC", "MatrizIPERC")
                        .WithMany("Detalles")
                        .HasForeignKey("MatrizIPERCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.SST.Entities.Peligro", "Peligro")
                        .WithMany("DetallesIPERC")
                        .HasForeignKey("PeligroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.Security.Entities.Usuario", "ResponsableImplementacion")
                        .WithMany()
                        .HasForeignKey("ResponsableImplementacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Consecuencia");

                    b.Navigation("EvaluacionInicial");

                    b.Navigation("EvaluacionResidual");

                    b.Navigation("MatrizIPERC");

                    b.Navigation("Peligro");

                    b.Navigation("ResponsableImplementacion");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.DetalleIPERCControl", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.Control", "Control")
                        .WithMany("DetalleIPERCControles")
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.IPERC.Entities.DetalleIPERC", "DetalleIPERC")
                        .WithMany("Controles")
                        .HasForeignKey("DetalleIPERCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("DetalleIPERC");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.DetalleIPERCEPP", b =>
                {
                    b.HasOne("SST.Domain.IPERC.Entities.DetalleIPERC", "DetalleIPERC")
                        .WithMany("EquiposProteccion")
                        .HasForeignKey("DetalleIPERCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.SST.Entities.EquipoProteccion", "EquipoProteccion")
                        .WithMany("DetalleIPERCEPPs")
                        .HasForeignKey("EquipoProteccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleIPERC");

                    b.Navigation("EquipoProteccion");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.EvaluacionRiesgo", b =>
                {
                    b.HasOne("SST.Domain.IPERC.Entities.NivelRiesgo", "NivelRiesgo")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("NivelRiesgoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.IPERC.Entities.Probabilidad", "Probabilidad")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("ProbabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.IPERC.Entities.Severidad", "Severidad")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("SeveridadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelRiesgo");

                    b.Navigation("Probabilidad");

                    b.Navigation("Severidad");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.MapaRiesgo", b =>
                {
                    b.HasOne("SST.Domain.IPERC.Entities.MatrizIPERC", "MatrizIPERC")
                        .WithMany()
                        .HasForeignKey("MatrizIPERCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatrizIPERC");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.MatrizIPERC", b =>
                {
                    b.HasOne("SST.Domain.Organization.Entities.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.Security.Entities.Usuario", "Aprobador")
                        .WithMany()
                        .HasForeignKey("AprobadorId");

                    b.HasOne("SST.Domain.Organization.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.Organization.Entities.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.Organization.Entities.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.Organization.Entities.PuestoTrabajo", "PuestoTrabajo")
                        .WithMany()
                        .HasForeignKey("PuestoTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.Security.Entities.Usuario", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SST.Domain.Organization.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Aprobador");

                    b.Navigation("Area");

                    b.Navigation("Institucion");

                    b.Navigation("Proceso");

                    b.Navigation("PuestoTrabajo");

                    b.Navigation("Responsable");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.SeguimientoIPERC", b =>
                {
                    b.HasOne("SST.Domain.IPERC.Entities.DetalleIPERC", "DetalleIPERC")
                        .WithMany("Seguimientos")
                        .HasForeignKey("DetalleIPERCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.Security.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleIPERC");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Actividad", b =>
                {
                    b.HasOne("SST.Domain.Organization.Entities.Institucion", null)
                        .WithMany("Actividades")
                        .HasForeignKey("InstitucionId");

                    b.HasOne("SST.Domain.Organization.Entities.Proceso", "Proceso")
                        .WithMany("Actividades")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Area", b =>
                {
                    b.HasOne("SST.Domain.Organization.Entities.Institucion", "Institucion")
                        .WithMany("Areas")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Proceso", b =>
                {
                    b.HasOne("SST.Domain.Organization.Entities.Area", "Area")
                        .WithMany("Procesos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.Organization.Entities.Institucion", null)
                        .WithMany("Procesos")
                        .HasForeignKey("InstitucionId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.PuestoTrabajo", b =>
                {
                    b.HasOne("SST.Domain.Organization.Entities.Area", "Area")
                        .WithMany("PuestosTrabajo")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.Organization.Entities.Institucion", null)
                        .WithMany("PuestosTrabajo")
                        .HasForeignKey("InstitucionId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Sede", b =>
                {
                    b.HasOne("SST.Domain.Organization.Entities.Institucion", "Institucion")
                        .WithMany("Sedes")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.Control", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.ClasificacionControl", "ClasificacionControl")
                        .WithMany("Controles")
                        .HasForeignKey("ClasificacionControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClasificacionControl");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.EquipoProteccion", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.TipoEquipoProteccion", "TipoEquipoProteccion")
                        .WithMany("EquiposProteccion")
                        .HasForeignKey("TipoEquipoProteccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEquipoProteccion");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.Peligro", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.TipoPeligro", "TipoPeligro")
                        .WithMany("Peligros")
                        .HasForeignKey("TipoPeligroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoPeligro");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.PeligroConsecuencia", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.Consecuencia", "Consecuencia")
                        .WithMany("PeligroConsecuencias")
                        .HasForeignKey("ConsecuenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.SST.Entities.Peligro", "Peligro")
                        .WithMany("PeligroConsecuencias")
                        .HasForeignKey("PeligroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consecuencia");

                    b.Navigation("Peligro");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.PeligroControl", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.Control", "Control")
                        .WithMany("PeligroControles")
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.SST.Entities.Peligro", "Peligro")
                        .WithMany("PeligroControles")
                        .HasForeignKey("PeligroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("Peligro");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.PeligroEquipoProteccion", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.EquipoProteccion", "EquipoProteccion")
                        .WithMany("PeligroEquiposProteccion")
                        .HasForeignKey("EquipoProteccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SST.Domain.SST.Entities.Peligro", "Peligro")
                        .WithMany("PeligroEquiposProteccion")
                        .HasForeignKey("PeligroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipoProteccion");

                    b.Navigation("Peligro");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.TipoPeligro", b =>
                {
                    b.HasOne("SST.Domain.SST.Entities.CategoriaPeligro", "CategoriaPeligro")
                        .WithMany("TiposPeligro")
                        .HasForeignKey("CategoriaPeligroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaPeligro");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.DetalleIPERC", b =>
                {
                    b.Navigation("Controles");

                    b.Navigation("EquiposProteccion");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.MatrizIPERC", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.NivelRiesgo", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.Probabilidad", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("SST.Domain.IPERC.Entities.Severidad", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Area", b =>
                {
                    b.Navigation("Procesos");

                    b.Navigation("PuestosTrabajo");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Institucion", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Areas");

                    b.Navigation("Procesos");

                    b.Navigation("PuestosTrabajo");

                    b.Navigation("Sedes");
                });

            modelBuilder.Entity("SST.Domain.Organization.Entities.Proceso", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.CategoriaPeligro", b =>
                {
                    b.Navigation("TiposPeligro");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.ClasificacionControl", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.Consecuencia", b =>
                {
                    b.Navigation("PeligroConsecuencias");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.Control", b =>
                {
                    b.Navigation("DetalleIPERCControles");

                    b.Navigation("PeligroControles");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.EquipoProteccion", b =>
                {
                    b.Navigation("DetalleIPERCEPPs");

                    b.Navigation("PeligroEquiposProteccion");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.Peligro", b =>
                {
                    b.Navigation("DetallesIPERC");

                    b.Navigation("PeligroConsecuencias");

                    b.Navigation("PeligroControles");

                    b.Navigation("PeligroEquiposProteccion");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.TipoEquipoProteccion", b =>
                {
                    b.Navigation("EquiposProteccion");
                });

            modelBuilder.Entity("SST.Domain.SST.Entities.TipoPeligro", b =>
                {
                    b.Navigation("Peligros");
                });
#pragma warning restore 612, 618
        }
    }
}
